### ISSUE TITLE
RFID ?

### ISSUE THREAD

**Issue by lidiotduvillage** [darryncampbell/EnterpriseBarcodePoC#1]
Hello,

Is there any chance to add methods to read and write RFID in this plugin ?
Thank you for that plugin, this is awesome

**Comment by darryncampbell** [comment]
Hi, there are no plans to add RFID to this plugin.  Couple of reasons:
- This plugin is based around the EMDK library which does not expose RFID capabilities itself
- I do not currently have any hardware available to me to develop / test against even if I was going to add it.
